services:
  postgres:
    image: postgres:15
    container_name: manufacture_db
    restart: always
    environment:
      POSTGRES_DB: manufacture_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - manufacture-net
  manufacture-service:
    image: psup-manufacture/manufacture-service
    container_name: manufacture-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/manufacture_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/manufacture_db
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONFIG_SERVER_USERNAME:myUsername
      - CONFIG_SERVER_PASSWORD:mySecretPassword
      - EUREKA_URL=http://eureka-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
      - STORAGE_SERVICE_BASE_URL=lb://STORAGE-SERVICE
      - KAFKA_BROKERS=broker-1:19092,broker-2:19092,broker-3:19092
      - KAFKA_DELIVERY_TIMEOUT_MS=20000
      - KAFKA_LINGER_MS=0
      - KAFKA_REQUEST_TIMEOUT_MS=10000
      - KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION=5
    volumes:
      - ~/Universal_Trade_Platform/logs/manufacture-service:/root/Universal_Trade_Platform/logs/manufacture-service
    networks:
      - manufacture-net
      - psup-shared-net

networks:
  manufacture-net:
    driver: bridge
  psup-shared-net:
    external: true