services:
  postgres:
    image: postgres:15
    container_name: manufacture_db
    restart: always
    environment:
      POSTGRES_DB: manufacture_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - manufacture-net
  manufacture-service:
    image: psup-manufacture/manufacture-service
    container_name: manufacture-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/manufacture_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/manufacture_db
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONFIG_SERVER_USERNAME:myUsername
      - CONFIG_SERVER_PASSWORD:mySecretPassword
      - EUREKA_URL=http://eureka-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
      - STORAGE_SERVICE_BASE_URL=lb://STORAGE-SERVICE
    networks:
      - manufacture-net
      - psup-shared-net

networks:
  manufacture-net:
    driver: bridge
  psup-shared-net:
    external: true