services:
  postgres:
    image: postgres:15
    container_name: manufacture_db
    restart: always
    environment:
      POSTGRES_DB: manufacture_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"